"""initial 2

Revision ID: 0a0223578324
Revises: aebf40c58d04
Create Date: 2024-01-22 22:32:36.126201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0223578324'
down_revision = 'aebf40c58d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('rules',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('rules',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
