"""up

Revision ID: 5c3b90887b35
Revises: 26d5a71f57ee
Create Date: 2024-01-23 21:58:59.042471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3b90887b35'
down_revision = '26d5a71f57ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('check_out_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('check_in_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
