"""initial 2

Revision ID: aebf40c58d04
Revises: 15dcd517b8f7
Create Date: 2024-01-22 22:31:16.486719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebf40c58d04'
down_revision = '15dcd517b8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('other_images',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('inclusives',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('amenities',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('inclusives',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('other_images',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
